Update easymap
EasyMap now checks for Nmap to be installed.

diff --git a/easymap b/easymap
--- a/easymap
+++ b/easymap
@@ -1,5 +1,29 @@
 #!/bin/bash
 
+check-for-nmap(){
+  if ! command -v nmap &> /dev/null; then
+    echo "nmap is not installed. Do you want to install it? (yes/no)"
+    read -r response
+    if [[ $response =~ ^yes$ ]]; then
+        if command -v apt-get &> /dev/null; then
+            sudo apt-get update && sudo apt-get install -y nmap
+        elif command -v yum &> /dev/null; then
+            sudo yum install -y nmap
+        elif command -v brew &> /dev/null; then
+            brew install nmap
+        else
+            echo "Unsupported package manager. Please install nmap manually."
+            exit 1
+        fi
+    else
+        echo "nmap is required to run this script. Exiting."
+        exit 1
+    fi
+  fi
+}
+
+check-for-nmap
+
 clear
 
 print-header(){
